apiVersion: batch/v1
kind: Job
metadata:
  name: delete-cluster-extension-resources
  annotations:
    "helm.sh/hook": pre-delete
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command: ["kubectl", "delete", "clusterrole,clusterrolebinding, clusterversions-reader", "appd-cluster-reader, {{ .Values.extensionServiceAccount }}"]
      restartPolicy: Never